name: Devops project real 4

on:
  push:
    branches: ["main"]

jobs:
  devops-real4-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setpu python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Formatting test
      run: black .
    
    - name: Lint test
      run: flake8 .
    
    - name: Static analysis
      run: bandit -r .

    - name: Unit test
      run: pytest test_app.py  
  
